version: "3.3"
services:
  pokegen_runner:
    image: dvcorg/cml-py3:latest
    environment: 
        - RUNNER_IDLE_TIMEOUT=0
        - RUNNER_LABELS=cml,gpu
        - RUNNER_REPO=https://github.com/Benjamin-Etheredge/pokegen
    shm_size: '24gb' # This fixes an issue with pytorch dataloaders
    runtime: nvidia
